version: '3.7'

services:

  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    container_name: mariadb
    environment:
      - MARIADB_USER=bn_jasperreports
      - MARIADB_DATABASE=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/bitnami
  
  jasperreports:
    image: docker.io/bitnami/jasperreports:7
    container_name: jasperreports
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=bn_jasperreports
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:8080'
    volumes:
      - jasperreports_data:/bitnami
    depends_on:
      - mariadb
